name: Create-Page

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches:
    - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: install-nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
          registry-url: 'https://registry.npmmirror.com/'
      
      - name: build-page
        run: |
          npm install pnpm -g
          pnpm install
          pnpm run page
      
      - name: push-page-to-branch-gh-pages
        env:
          TOKEN: ${{ secrets.pageToken }}
          REF: github.com/${{github.repository}}
          MYEMAIL: 329106954@qq.com 
          MYNAME: ${{github.repository_owner}}
        run: |
          cd page
          git config --global user.email "${MYEMAIL}"   
          git config --global user.name "${MYNAME}"   
          git init  
          git remote add origin https://${REF}
          git add .
          git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
          git branch -M main
          git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages